dist: trusty
language: node_js
node_js:
  - "12"
env:
    - JWT_SECRET=superjwtsecret
    - SESSION_SECRET=supersessionsecret
jobs:
  fast_finish: true

install:
    - cd backend
    - yarn

script:
    - "yarn test"